tag: 丹恒
type: month  # 可以在date, week, month, total中选择

turn: 
  - 10   # 起始位 从第10*n+1个帖子开始抓取
  - 13   # 终止位 终止于第n*10个帖子
  # 抓取帖子数（填入n，抓取n*10个帖子） 必须保证为整数 受Lofter API限制，目前最多抓取前1000个帖子 （即n=100） 之后返回空内容
  # 不建议在week和date中填太大的起始位和终止位，除非你对这是一个大热的tag非常自信，或者能忍耐满屏报错并且卡你十几秒
specified:  #如果运行时部分有报错，或者想抓特定范围的帖子，参照Turn格式填写目标位置
            #注意，该参数优先级高，会对Turn执行override

likes:          #抓取点赞数大于等于该数的帖子（可能存在少部分小于该数的帖子）  不需要就不填